### ISSUE TITLE
Investigate heisenbug with db AddBatch()

### ISSUE THREAD

**Issue by Avokadoen** [nlnwa/gowarc#19]
#### Issue description

A heisenbug which causes gowarc to panic at db AddBatch()

#### Steps to reproduce the issue

Currently unknown, but indexing many warcs increase the odds

#### What's the expected result?

All warcs are either indexed or some report errors i.e invalid file content 

#### What's the actual result?

Some warcs causes gowarc to panic at random

#### Additional details / screenshot

Panic stack trace
```txt
panic: runtime error: invalid memory address or nil pointer dereference                       
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa0a59c]                       
goroutine 23 [running]:                                                                       
github.com/nlnwa/gowarc/pkg/index.(*Db).AddBatch.func1(0xc517e22980, 0x450001, 0xc517e22980)  
        /build/pkg/index/db.go:253 +0x8c                                                      
github.com/dgraph-io/badger/v2.(*DB).Update(0xc0001ce800, 0xc78fa4bf50, 0x0, 0x0)             
        /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.2/txn.go:696 +0x94                    
github.com/nlnwa/gowarc/pkg/index.(*Db).AddBatch(0xc0001d7ab0, 0xc4fd83e000, 0x2711, 0x2711)  
        /build/pkg/index/db.go:251 +0x100                                                     
github.com/nlnwa/gowarc/pkg/index.NewIndexDb.func1(0xc0001d7ab0, 0xc0000e8e40)                
        /build/pkg/index/db.go:79 +0x71                                                       
created by github.com/nlnwa/gowarc/pkg/index.NewIndexDb                                       
        /build/pkg/index/db.go:77 +0x31a  
```

**Comment by Avokadoen** [comment]
From current master  
```txt
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server panic: runtime error: invalid memory address or nil pointer dereference
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa0a91c]
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server 
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server goroutine 11 [running]:
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server github.com/nlnwa/gowarc/pkg/index.(*Db).AddBatch.func1(0xc07b440180, 0x1, 0xc07b440180)
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server         /build/pkg/index/db.go:230 +0x8c
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server github.com/dgraph-io/badger/v2.(*DB).Update(0xc00001ec00, 0xc09cd2df50, 0x0, 0x0)
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server         /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.2/txn.go:696 +0x94
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server github.com/nlnwa/gowarc/pkg/index.(*Db).AddBatch(0xc00018cf50, 0xc07b434000, 0xc5, 0xc5)
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server         /build/pkg/index/db.go:228 +0x100
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server github.com/nlnwa/gowarc/pkg/index.NewIndexDb.func1(0xc00018cf50, 0xc0000a6ea0)
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server         /build/pkg/index/db.go:80 +0x71
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server created by github.com/nlnwa/gowarc/pkg/index.NewIndexDb
loke-gowarc-server-noall-848ccf4948-gz8hn gowarc-server         /build/pkg/index/db.go:78 +0x31a
```

**Comment by maeb** [comment]
The fix may be to update badger and not related to https://github.com/nlnwa/gowarc/issues/19.
