### ISSUE TITLE
Bug when running index with specified path

### ISSUE THREAD

**Issue by Avokadoen** [nlnwa/gowarc#7]
#### Issue description
Running `warc index ./testdata/IAH-20080430204825-00000-blackbook.warc`  results in an runtime error where the program tries to dereference invalid memory.

#### Steps to reproduce the issue

1. clone repo from master branch
2. build the project
3. do `./warc index ./testdata/IAH-20080430204825-00000-blackbook.warc` in root

#### What's the expected result?

- gowarc index warc file OR an error message describing user error

#### What's the actual result?

dump:
```txt
Using config file: /home/aksel/Projects/gowarc/config.yaml
Format: { <nil>}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa124b5]

goroutine 1 [running]:
github.com/nlnwa/gowarc/cmd/warc/cmd/index.runE(0xc0000d4dc0, 0x0, 0x0)
        /home/aksel/Projects/gowarc/cmd/warc/cmd/index/index.go:88 +0xd5
github.com/nlnwa/gowarc/cmd/warc/cmd/index.NewCommand.func1(0xc00012f900, 0xc000122060, 0x1, 0x1, 0x0, 0x0)
        /home/aksel/Projects/gowarc/cmd/warc/cmd/index/index.go:77 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc00012f900, 0xc000122020, 0x1, 0x1, 0xc00012f900, 0xc000122020)
        /home/aksel/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00012ef00, 0xc000000180, 0xc00018ff78, 0x411905)
        /home/aksel/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /home/aksel/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/aksel/Projects/gowarc/cmd/warc/main.go:26 +0x2b
```

**Comment by Avokadoen** [comment]
Resolved in https://github.com/nlnwa/gowarc/pull/27
